name: Deploy to Development

on:
  pull_request:
    types: [opened, edited, reopened, ready_for_review, synchronize]

env:
  DOCKER_COMPOSE_VERSION: 1.29.2

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: 🔑 Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 🐳 Build and push Docker image for swee url
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/swee-url-dev:latest -f Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/swee-url-dev:latest

      - name: 🔓 Logout from Docker Hub
        run: docker logout

      - name: 🚀 Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DEV }}
          username: ${{ secrets.USERNAME_DEV }}
          password: ${{ secrets.SSH_PASSWORD_DEV }}
          script: |
            cd ~/eventbadge/swee-url

            # Stop and remove the containers
            docker-compose -f docker-compose.dev.yml down

            # Pull the latest images
            docker-compose -f docker-compose.dev.yml pull

            # Rebuild and restart the services
            docker-compose -f docker-compose.dev.yml up --build -d

            # Cleanup Docker
            docker system prune -f
            docker volume prune -f
            docker image prune -a -f
            docker container prune -f